### ISSUE TITLE
Error: Evaluation failed: TypeError: Cannot read property 'innerText' of null

### ISSUE THREAD

**Issue by nghilevi** [hpt-dev/QuickScrape#3]
Hi,

I tried a simple task like this, but got the above error

```
const webpagedatascraper = require('webpagedatascraper');
 
(async () => {
    let urls = [
        'https://www.etoro.com/people/cashflowstation/stats'
    ];
    
    let selectors =
    {
        Text: {
			copiers: '.info-procents'
		},
        Tables: {},
        Images: {}
    };
  
    let actual = await webpagedatascraper.scrape(urls, selectors);
    
    console.log(actual);
})()

```

If I, however, change '.info-procents' to a different class for example '.instrument-navigation-link-top-name', then it works. So it may work with some classes, and some it does not.

**Comment by nghilevi** [comment]
Same problem when I tried with purely puppeteer
I opened an issue here: https://github.com/puppeteer/puppeteer/issues/6694

**Comment by hpt-dev** [comment]
Hi vinhnghi223 do you still need help with this issue? Sorry for the late response.

**Comment by hpt-dev** [comment]
Hi vinhnghi223, will have a look at this

**Comment by hpt-dev** [comment]
Issue raised and closed on pupeteer issue page

**Comment by hpt-dev** [comment]
Update: This example failed because it is not using the correct selectors. An example selector should look like this:

'body > div.container > div.col-left > div > section:nth-child(3) > div > div.fighter-info > div.fighter-right > div.fighter-data > div.winsloses-holder > div.wins > div:nth-child(3) > div.pl',

How to get the css selectors using google chrome (don't use firefox as the options are different):
    1. Hover the cursor over the image, text, or table you wish to scrape and right click mouse.
    2. Select Inspect which will bring up the chrome developer tools.
    3. Right click on the highlighted image tag, tag that contains the text (e.g. span, p, b) or the table tag.
    4. Select Copy > CSS selector (this is important! The path should have '>' symbols in like the examples in the readme file).

Thanks,
hptdev

**Comment by hpt-dev** [comment]
After trying the above example with headless mode set to true I realised that eToro is redirecting to a login page so even if you had used the correct selectors it wouldn't have worked. It doesn't happen when you visit the URL in a regular browser so maybe they are able to detect if the page is being run in a pupetter instance to prevent scraping?
